version: '3'
name: template-dev-environment
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
